USE db_myquiz;

INSERT INTO User VALUES (1, "alanz", "123456", "Alan", "Zhang", "Boston", "haoyuz0214@gmail.com", "8573089078", True, False),
 						(2, "admin", "admin", "adminAlan", "adminZhang", "Boston", "haoyuz0214@gmail.com", "8573089078", True, True),
						(3, "user3", "pass3", "firstname3", "lastname3", "NJ", "nj123@gmail.com", "12345567", True, False);

INSERT INTO Category VALUES(1, "Programming"),
						   (2, "History"),
                           (3, "Literature");
                           
INSERT INTO Quiz VALUES (1, 1, "Java"),
						(2, 2, "Chinese History"),
                        (3, 3, "American Literature");

-- INSERT INTO QuizRecord VALUES(1, 1, 1, "2022-12-30 14:00:00", 100),
-- 							 (2, 2, 1, "2022-12-28 08:30:00", 80);
                             
INSERT INTO Question VALUES(1, 1, "Which is not directly related to Java?", true),
						   (2, 1, "Which is not primitive data type in Java?", true),
						   (3, 1, "Whose answer is yes about static method?", true),
						   (4, 1, "Can final method be overriden?", true),
                           (5, 1, "Is static a non-access modifier?", true),
						   (6, 2, "How long did it take to build the Great Wall?", true),
						   (7, 2, "When did China become an empire?", true),
                           (8, 2, "What is the Terracotta Army made from?", true),
                           (9, 2, "What were wealthy people's clothes made from in ancient China?", true),
                           (10, 2, "Which was not invented in ancient China?", true),
                           (11, 3, "Who wrote The Da Vinci Code?", true),
						   (12, 3, "Which American novelist wrote For Whom the Bell Tolls?", true),
                           (13, 3, "What do the initials J. D. stand for in author J. D. Salinger’s name?", true),
                           (14, 3, "Who wrote East Of Eden?", true),
                           (15, 3, "What is the only novel to top the best-seller lists for two consecutive years?", true);

INSERT INTO Options VALUES(1, 1, "JSTL", false),
						  (2, 1, "JSP", false),
                          (3, 1, "Tensorflow", true),
                          (4, 1, "JDBC", false),
                          (5, 2, "String", true),
                          (6, 2, "int", false),
                          (7, 2, "double", false),
                          (8, 2, "float", false),
						  (9, 3, "Access instance variables?", false),
						  (10, 3, "Access static class variables", true),
                          (11, 3, "Call non-static instance methods?", false),
                          (12, 3, "Use the object reference this?", false),
                          (13, 4, "Yes", false),
                          (14, 4, "No", true),
                          (15, 5, "Yes", true),
                          (16, 5, "No", false),
						  (17, 6, "1000 years", false),
						  (18, 6, "Over 2000 years", true),
						  (19, 6, "200 years", false),
                           (20, 6, "5000 years", false),
                           (21, 7, "1912", false),
						   (22, 7, "1949", false),
                           (23, 7, "1368", false),
                           (24, 7, "221 BCE", true),
                           (25, 8, "Straw", false),
						   (26, 8, "Clay", true),
                           (27, 8, "Wood", false),
                           (28, 8, "Stone", false),
                           (29, 9, "Nylon", false),
						   (30, 9, "Cotton", false),
                           (31, 9, "Silk", true),
                           (32, 9, "Hemp", false),
                           (33, 10, "Gunpowder", false),
						   (34, 10, "Magnetic compass", false),
                           (35, 10, "Bicycle", true),
                           (36, 10, "Earthquake monitor", false),
                           (37, 11, "Hugo", false),
						   (38, 11, "Flaubert", false),
                           (39, 11, "Dan Brown", true),
                           (40, 11, "Jobs", false),
                           (41, 12, "Hugo", false),
						   (42, 12, "Marx", false),
                           (43, 12, "Ernest Hemingway", true),
                           (44, 12, "Lily", false),
                           (45, 13, "James David", false),
						   (46, 13, "Jelly David", false),
                           (47, 13, "Jerome David", true),
                           (48, 13, "Jeremy David", false),
                           (49, 14, "Nick", false),
						   (50, 14, "Ernest Hemingway", false),
                           (51, 14, "John Steinbeck", true),
                           (52, 14, "Frandy", false),
                           (53, 15, "Franklin", false),
						   (54, 15, "Tobe Smith", false),
                           (55, 15, "Jonathan Livingston Seagull", true),
                           (56, 15, "Nobody knows", false);

INSERT INTO Feedback VALUES (1, 1, 4, "A good quiz application.", "2023-01-02 14:20:03");

INSERT INTO Permission VALUES (1, "read"),
							  (2, "write"),
                              (3, "update"),
                              (4, "delete");

INSERT INTO UserPermission VALUES (1, 1, 1),
								  (2, 1, 2),
                                  (3, 2, 1),
                                  (4, 2, 2),
                                  (5, 2, 3),
                                  (6, 2, 4),
                                  (7, 3, 1),
								  (8, 3, 2);